### PR TITLE
local development quickstart

### PR DESCRIPTION
**Pull request by kaihendry**

### CODE REVIEW

**Comment by djh42** [comment]
No issues allowed, so here's a non-sequitur comment. :( When I look at https://grid.iamkate.com/ and click on one of the grey question marks I see a white popup with a black x in the top right. But clicking on the x doesn't dismiss the dialog - I have to refresh the page instead to get rid of it. So the site is broken. FF 115.6.0esr (64-bit).

**Comment by bitrivers** [comment]
Hi. Also abusing the comments here just to let you know that your headline emissions figure on your wonderful grid page has been unreliable over the past few weeks. For instance now (11:40 17/6/24) it’s showing 46g/kWh while 6.6GW (20.9%) gas in use, by comparison the past day reading is 92g/kWh corresponding to 4.2GW (16.2%) gas burn. The longer term graph trace of emissions looks much more plausible. Thx

**Review by jujhars13 — APPROVED** [review]
lgtm

**Comment by KateMorley** [comment]
Thank you for your suggested changes, but I’ve chosen to use the lightweight php:cli-alpine and nginx:alpine-slim images rather than the heavyweight frankenphp image.

**Pull request closed without merging**
